name: sliver_dashboard
description: "High-performance, sliver-based draggable and resizable grid engine for Flutter. Supports responsive layouts and collision handling."
homepage: https://github.com/scalz/sliver_dashboard
repository: https://github.com/scalz/sliver_dashboard
issue_tracker: https://github.com/scalz/sliver_dashboard/issues
version: 0.7.0

environment:
  sdk:  ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  state_beacon: ^1.3.2

dev_dependencies:
  coverage: ^1.15.0

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  meta: ^1.16.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

topics:
  - dashboard
  - grid
  - layout
  - draggable
  - resizable